WFLY-15642 Kitchen Sink quickstart uses outdated EAP logo
wildfly/quickstart pull request #535
Opened 2021-11-09 11:27 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/WFLY-15642

2021-11-09 19:36 UTC, jamezp commented
I'm not sure this is quite right for a community project. Also the logo is massive so it would need something like `width="300"` on the `img` element.

2021-11-09 19:43 UTC, RanabirChakraborty commented
An issue was created for `jboss-eap-quickstart`, so I thought to change here as well. I can change the width but If you think for the community project it's not required, then I can close the PR.

2021-11-12 16:21 UTC, jamezp commented
I still think we should be using the community logo here.

2021-11-12 17:20 UTC, emmartins commented
It should be a logo good for both Wildfly and EAP

2021-11-15 10:02 UTC, RanabirChakraborty commented
@emmartins if possible can you please suggest to me any logo?

2021-11-25 19:24 UTC, emmartins commented
@RanabirChakraborty sorry but missed notification of your question, perhaps the JBoss by Red Hat logo?

2021-11-25 21:14 UTC, RanabirChakraborty commented
@emmartins will this be good to use? - [here](https://upload.wikimedia.org/wikipedia/commons/9/95/JBoss_logo.svg)

2021-12-06 15:47 UTC, emmartins commented
@RanabirChakraborty IMO yes

2021-12-09 16:07 UTC, emmartins requested changes

2021-12-09 16:07 UTC, emmartins commented on hibernate/src/main/webapp/WEB-INF/templates/default.xhtml
> +         <img src="resources/gfx/rhjb_eap_logo.png" width="300" height="60" />
The height should be 175, to keep the logo's original aspect ratio.

2021-12-09 16:07 UTC, emmartins commented on kitchensink-angularjs/src/main/webapp/index.html
> +            <img src="gfx/rhjb_eap_logo.png" width="300" height="60" />
The height should be 175, to keep the logo's original aspect ratio.

2021-12-09 16:07 UTC, emmartins commented on kitchensink-ear/web/src/main/webapp/WEB-INF/templates/default.xhtml
> +         <img src="resources/gfx/rhjb_eap_logo.png" width="300" height="60"/>
The height should be 175, to keep the logo's original aspect ratio.

2021-12-09 16:07 UTC, emmartins commented on kitchensink-jsp/src/main/webapp/index.jsp
> +            <img src="resources/gfx/rhjb_eap_logo.png" width="300" height="60" />
The height should be 175, to keep the logo's original aspect ratio.

2021-12-09 16:07 UTC, emmartins commented on kitchensink-ml/src/main/webapp/WEB-INF/templates/default.xhtml
> +            <img src="resources/gfx/rhjb_eap_logo.png" width="300" height="60"/>
The height should be 175, to keep the logo's original aspect ratio.

2021-12-09 16:07 UTC, emmartins commented on kitchensink/src/main/webapp/WEB-INF/templates/default.xhtml
> +            <img src="resources/gfx/rhjb_eap_logo.png" width="300" height="60" />
The height should be 175, to keep the logo's original aspect ratio.

2021-12-09 16:07 UTC, emmartins commented on payment-cdi-event/src/main/webapp/WEB-INF/templates/template.xhtml
> +         <img src="resources/gfx/rhjb_eap_logo.png" width="300" height="60"/>
The height should be 175, to keep the logo's original aspect ratio.

2021-12-09 16:07 UTC, emmartins commented on spring-kitchensink-basic/src/main/webapp/WEB-INF/views/index.jsp
> +        <img src="<c:url value="/static/resources/gfx/rhjb_eap_logo.png"/>" width="300" height="60"/>
The height should be 175, to keep the logo's original aspect ratio.

2021-12-09 16:07 UTC, emmartins commented on spring-kitchensink-springmvctest/src/main/webapp/WEB-INF/views/index.jsp
> +        <img src="<c:url value="/static/resources/gfx/rhjb_eap_logo.png"/>" width="300" height="60"/>
The height should be 175, to keep the logo's original aspect ratio.

2022-01-04 07:12 UTC, RanabirChakraborty commented
Thanks, @emmartins Did the changes :)

2022-02-23 05:17 UTC, RanabirChakraborty commented
@emmartins Can you please take a look.

2022-03-24 07:23 UTC, merged