[WFLY-13257] Improvements for MicroProfile Fault Tolerance quickstart
wildfly/quickstart pull request #655
Opened 2023-03-15 15:38 UTC by ChristinaDsl

https://issues.redhat.com/browse/WFLY-13257
In this issue, is presented the functionality of Bulkhead annotation in detail, implemented in a method.

2023-06-15 08:59 UTC, emmartins commented
@pferraro @rhusar not sure who is now the responsible for this QS, my guess it's one of you, please review

2023-06-15 09:37 UTC, rhusar commented
> @pferraro @rhusar not sure who is now the responsible for this QS, my guess it's one of you, please review


@emmartins It's me. I can't assign myself as reviewer - can you please fix the project permissions settings? Thanks!

2023-06-20 08:18 UTC, rhusar requested changes

2023-06-20 08:18 UTC, rhusar commented on microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeRepositoryService.java
> +    public Coffee getOrder(){
Run a formatter here, there is a missing space.

2023-06-20 08:18 UTC, rhusar commented on microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeRepositoryService.java
> +        Coffee order = coffeeList.get((int )(Math.random() * coffeeList.size() + 1));
Also run formatter here.

2023-06-20 08:18 UTC, rhusar commented on microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeResource.java
> +        this.numberOfThreads=numberOfThreads;
Run a formatter here - missing spaces.

2023-06-20 08:18 UTC, rhusar commented on microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeResource.java
> +        sleep(new Random().nextInt(500));
Not a fan of a static import here.

2023-08-02 10:33 UTC, ChristinaDsl commented
@rhusar Is there anything else that you need from my side?

2025-09-10 11:26 UTC, emmartins commented
@ChristinaDsl @rhusar  FYI housekeeping, about to close this old PR, I guess that at most we need a new PR migrating any changes to current testing code?

2025-09-11 11:04 UTC, iweiss commented
Christina is no longer working on this

2025-09-11 12:52 UTC, emmartins commented
@iweiss thanks for the info
@rhusar closing this, please create a new PR if you want to reuse the changes on this

2025-09-11 12:52 UTC, closed without merging