[WFLY-17740] Add missing @fallback test in Microprofile Fault Tolerance quickstart
wildfly/quickstart pull request #656
Opened 2023-03-17 08:51 UTC by ChristinaDsl

In this issue were added two Test methods, both testing a method with @Fallback annotation . The first one tests the successful execution of the method, which also has specific time frame (with the help of @Timeout). The second one secures that every time the execution time of the method exceeds the time limit, the Fallback method executed successfully.

2023-03-20 07:14 UTC, iweiss commented
Please add the link to the issue tracker on the first line

2023-06-15 08:59 UTC, emmartins commented
@pferraro @rhusar not sure who is now the responsible for this QS, my guess it's one of you, please review

2023-06-15 09:03 UTC, rhusar commented
@emmartins I can't assign myself as reviewer - can you please fix the project permissions settings? Thanks!

2023-06-20 08:16 UTC, rhusar requested changes

2023-06-20 08:16 UTC, rhusar commented on microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeResource.java
> +    private void randomDelay() throws InterruptedException  {
The extra new space here is wrong.

2023-06-20 08:16 UTC, rhusar commented on microprofile-fault-tolerance/src/test/java/org/wildfly/quickstarts/microprofile/faulttolerance/MicroProfileFaultToleranceITest.java
> +public class MicroProfileFaultToleranceITest {
The rename here is unnecessary and would make this out of sync with other quickstarts in this category.

2023-06-20 08:16 UTC, rhusar commented on microprofile-fault-tolerance/src/main/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeResource.java
> +    @Timeout(value = 250)
This change is unnecessary and also inconsistent with e.g. the annotation above it. The `value =` is implicit

2023-06-20 12:23 UTC, ChristinaDsl commented
@rhusar Thank you. All changes have been made.

2023-08-02 10:32 UTC, ChristinaDsl commented
@rhusar Is there anything else that you need from my side?

2023-08-02 13:30 UTC, rhusar commented
> @rhusar Is there anything else that you need from my side?

Nope - just competing priorities on my side...

2023-12-15 11:48 UTC, emmartins requested changes
The quickstart testing has been fully reworked, please rebase and update changes.

2023-12-20 13:34 UTC, rhusar requested changes
@ChristinaDsl Please review the prior changes to the testing and note that we have removed ARQ and reworked to use a remote client istead.

2023-12-20 13:34 UTC, rhusar commented on microprofile-fault-tolerance/pom.xml
> +        </dependency>
Remove this as this won't work when testing against deployment running in e.g. OpenShift.

2023-12-20 13:34 UTC, rhusar commented on microprofile-fault-tolerance/pom.xml
> +        </dependency>
Remove this as this won't work when testing against deployment running in e.g. OpenShift.

2023-12-20 13:34 UTC, rhusar commented on microprofile-fault-tolerance/src/test/resources/arquillian.xml
> +</arquillian>
We no longer use ARQ. Remove this as this won't work when testing against deployment running in e.g. OpenShift.

2023-12-20 13:34 UTC, rhusar commented on microprofile-fault-tolerance/src/test/java/org/wildfly/quickstarts/microprofile/faulttolerance/CoffeeResourceIT.java
> +    CoffeeRepositoryService coffeeRepository;
Remove this as this won't work when testing against deployment running in e.g. OpenShift.

2023-12-21 11:28 UTC, ChristinaDsl commented
@rhusar thanks for your comments. I will manage the fixes.

2024-01-19 13:24 UTC, emmartins commented
@ChristinaDsl please verify the new test, one run on CI did fail

2024-01-19 13:41 UTC, rhusar commented
@emmartins Yet again - could you please verify the permissions for this repository? I can't even mark (my own) conversations as resolved...

2024-01-19 14:21 UTC, emmartins commented
@rhusar if I find that option... yes sure!!!!

2024-01-19 14:22 UTC, rhusar commented
> @rhusar if I find that option... yes sure!!!!

I am going to guess that it's just the triage permission.

2024-01-19 14:27 UTC, emmartins commented
can you please recheck now?

2024-01-22 14:02 UTC, ChristinaDsl commented
@emmartins  Sure.

2024-04-03 14:26 UTC, emmartins commented
Merging since testsuite seems stable now, if an intermitent pops up again will open an issue, thanks @ChristinaDsl

2024-04-03 14:26 UTC, merged

2024-04-03 18:01 UTC, rhusar commented
Thanks @ChristinaDsl  and @emmartins !

2024-04-05 07:43 UTC, ChristinaDsl commented
Thank you too @emmartins and @rhusar!