[WFLY-18466] ejb-security-context-propagation Quickstart Common Enhan…
wildfly/quickstart pull request #751
Opened 2023-10-17 17:46 UTC by PrarthonaPaul

…cements CY2023Q3
Issue: https://issues.redhat.com/browse/WFLY-18466
Note: This QS is open shift incompatible, requires adding users using `add-user.sh` file and does not have a web endpoint, instead we use mvn exec:exec to check the output.

2023-10-24 11:09 UTC, emmartins requested changes
Besides the pointed needed changes there is also the missing update for the README.adoc... 
But this QS is again an example of where we need deeper changes, in this particular case the troubles are mostly around the usage of exec:exec, which should be replaced by functional integration testing. There are a few things I need to add also to shared resources, so this time I will send you a PR with all the fixes.

2023-10-24 14:06 UTC, PrarthonaPaul commented on ejb-security-context-propagation/pom.xml
> +                <plugin>
Hi @emmartins 
I am not sure what to do for this one. 
Should I move this plugin to the integration-testing profile?

2023-10-24 14:15 UTC, PrarthonaPaul commented on .github/workflows/quickstart_ejb_security_context_propagation_ci.yml
> +name: WildFly ejb-security-context-propagation Quickstart CI
Fixed!

2023-10-24 14:15 UTC, PrarthonaPaul commented on .github/workflows/quickstart_ejb_security_context_propagation_ci.yml
> +# Only run the latest job
Fixed!

2023-10-24 14:17 UTC, PrarthonaPaul commented on ejb-security-context-propagation/pom.xml
> +                                <layer>cloud-server</layer>
Added.

2023-10-24 14:17 UTC, PrarthonaPaul commented on ejb-security-context-propagation/src/main/java/org/jboss/as/quickstarts/ejb_security_context_propagation/EJBServlet.java
> +    static String PAGE_HEADER = "<html><head><title>helloworld</title></head><body>";
fixed

2023-10-24 14:18 UTC, PrarthonaPaul commented on ejb-security-context-propagation/src/main/java/org/jboss/as/quickstarts/ejb_security_context_propagation/EJBServlet.java
> +        writer.println("<h1> Hello World! </h1>");
Fixed! 
I also added the missing updates to the README file. If there is anything else I should do, please let me know! Thanks

2023-10-26 20:41 UTC, merged

2023-10-26 20:41 UTC, emmartins commented
thank you @PrarthonaPaul