WFLY-18488 jts Quickstart Common Enhancements CY2023Q3
wildfly/quickstart pull request #773
Opened 2023-11-10 12:55 UTC by mmusgrov

https://issues.redhat.com/browse/WFLY-18488

The changes include clarifying the test setup and disabling testing on Openshift since setting up and coordinating multiple servers is not technically feasible without incurring a lot of effort.

2023-11-15 09:47 UTC, emmartins requested changes
Hi @mmusgrov , considering the QS complexity I agree there is no point (at least now) in targeting OpenShift compatibility, and I believe the same may be said about server provisioning. Still there are are few things missing:
* the CI yaml for this quickstart, which should specify the optional params TEST_OPENSHIFT and TEST_PROVISIONED_SERVER as false
* wildfly plugin management in the pom.xml

2023-11-15 10:00 UTC, mmusgrov commented
Ah, I had those but forgot to git add the new file, sorry about that, I will update the PR.

2023-11-20 13:34 UTC, emmartins approved these changes

2023-11-20 13:34 UTC, merged

2023-11-20 13:35 UTC, emmartins commented
thank you @mmusgrov