[WFLY-18768] OpenShift support for the mail quickstart
wildfly/quickstart pull request #923
Opened 2024-05-31 10:26 UTC by Dkafetzis

https://issues.redhat.com/browse/WFLY-18768

2024-06-17 18:27 UTC, emmartins commented
hi @Dkafetzis , I am delegating review to @yersan , who leads mail's component

2024-07-04 11:02 UTC, yersan commented
/ok-to-test

2024-07-04 12:13 UTC, yersan requested changes
Hello @Dkafetzis , you did great work with this, thanks!

I've added minor notes to review, also, when I compile the mail server locally, the readme.html generated does not contain all the steps related to helm charts and OpenShift, what is the trick to read the final documentation generated from this soruces?

2024-07-04 12:13 UTC, yersan commented on mail/helm-install-prerequisites.adoc
> +=== Install OpenTelemetry Collector on OpenShift
This title is not correct, it should be "Install the Mail server on Openshift" or something like that

2025-02-11 10:37 UTC, Dkafetzis commented on mail/README.adoc
> +The backend will be built and deployed on OpenShift with a Helm Chart for {productName}.
This is part of a shared doc that gets generated once the asciidoctor flattens the README-source.adoc file. So it is the same for everyone that references it

2025-02-11 13:35 UTC, emmartins commented on mail/README.adoc
> +The backend will be built and deployed on OpenShift with a Helm Chart for {productName}.
FYI no need to update manually this file, once the PR is merged this will be auto updated

2025-02-11 13:36 UTC, emmartins commented on mail/README.adoc
> +The backend will be built and deployed on OpenShift with a Helm Chart for {productName}.
@yersan FYI you can use -Pdocs or -Drelease to rebuild the html

2025-02-11 13:40 UTC, emmartins commented on mail/configure-mail-session.cli
> +reload
please revert the reload, this is done automatically by the WildFly Maven Plugin, and it is responsible for some intermittent CI fails

2025-02-11 14:19 UTC, emmartins approved these changes
The changes looks good to me. If CI testing is green and @yersan approves too I will merge it.

2025-02-11 14:24 UTC, emmartins commented on mail/pom.xml
> +                            <filename>ROOT.war</filename>
please remove this, it is the reason of CI fails

2025-02-11 14:40 UTC, Dkafetzis commented on mail/pom.xml
> +                            <filename>ROOT.war</filename>
Done

2025-02-11 15:37 UTC, emmartins approved these changes
Please note that Kubernetes support will be needed to overcome the CI fail, but this can be done in a separated JIRA and PR. In case you want to do it here and now please let me know so I point you in the right direction.

2025-02-11 15:42 UTC, Dkafetzis commented
@emmartins  I'd like to also add support for kubernetes on the quickstart but In another issue since this is not part of Openshift and this one has been open for a long time.

2025-03-07 09:45 UTC, emmartins commented
@Dkafetzis FYI not forgotten, just waiting for additional @kstekovi review, who will later add some testing changes on top of your work, this may take a week or more

2025-03-26 23:03 UTC, emmartins requested changes
hi @Dkafetzis, I was trying your branch with Openshift sandbox, to finally merge this PR, but there is a major issue, there are no README instructions wrt the greenmail Helm Chart install. This should be done similar to how microprofile-reactive-messaging-kafka extends its README-source.adoc ( by adding an extra adoc file and pointing an attr to it, please see https://github.com/wildfly/quickstart/blob/f242714588530e5ca66522953a53304ae04d18da/microprofile-reactive-messaging-kafka/README-source.adoc?plain=1#L10 ) 

Unfortunately I was not able to just use the traditional command we use for extras, which would be "oc apply -f ./charts/greenmail-openshift.yaml --wait --timeout=10m0s", and succeed with the standard openshift test command "$ mvn verify -Pintegration-testing -Dserver.host=https://$(oc get route mail --template='{{ .spec.host }}')"

I know this one has not been easy to make everyone happy, but in this case we really need fully working OpenShift instructions.

2025-03-31 14:40 UTC, emmartins commented
Thanks @Dkafetzis, I will check it as soon as possible.

2025-08-25 13:14 UTC, emmartins approved these changes

2025-08-25 13:18 UTC, emmartins commented
@kstekovi I am available to merge this. I have tested it myself and it looks good to me. If you wanna test it yourself please note that you will need to manually change the helm chart, to refer @Dkafetzis branch.

2025-08-26 08:34 UTC, kstekovi commented on mail/src/main/webapp/home.xhtml
> +        Retrieve emails for the user01@mail.local account using IMAP:
It will retrieve emails for the user02. see a default IMAP configuration. 
https://github.com/Dkafetzis/quickstart/blob/WFLY-18768/mail/configure-mail-session.cli#L17

2025-08-26 10:41 UTC, Dkafetzis commented on mail/src/main/webapp/home.xhtml
> +        Retrieve emails for the user01@mail.local account using IMAP:
@kstekovi True, no idea why the page mentioned user01, changed the xhtml line to user02.

2025-08-26 11:46 UTC, kstekovi commented on mail/src/test/java/org/jboss/as/quickstarts/mail/MailTestCaseIT.java
I notice selenium logs a few warnings, but it could be solved by using HTML unit instead selenium. see this open PR https://github.com/wildfly/quickstart/pull/1009

> Aug 26, 2025 10:35:04 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find CDP implementation matching 139

2025-08-26 11:46 UTC, kstekovi approved these changes

2025-08-26 12:11 UTC, emmartins commented on mail/src/test/java/org/jboss/as/quickstarts/mail/MailTestCaseIT.java
Ok, let's have a look into that in the context of https://issues.redhat.com/browse/WFLY-20129

2025-08-26 14:34 UTC, merged

2025-08-26 14:38 UTC, emmartins commented
@Dkafetzis thank you very much for this, it's good stuff, and of course, very sorry for the long delay!

Next we are going to have another look at the testing, since we have changed it on product side, and any changes I will ping you to participate on review, in case you are interested of course. 

I will also create a JIRA for the work wrt Kubernetes, if you interested on that too please let me know.