[WFLY-19359] define kafka yaml file for OpenShift and update the README.
wildfly/quickstart pull request #929
Opened 2024-06-11 13:55 UTC by kstekovi

https://issues.redhat.com/browse/WFLY-19408

Define AMQ stream operator, instance and topic in a  yaml file for OpenShift and update the README.

2024-06-11 14:05 UTC, emmartins commented
@kstekovi thanks, @kabir please review

2024-06-11 14:17 UTC, kabir requested changes
The CI should also be updated to use this file.

OpenShift: 
https://github.com/wildfly/quickstart/blob/main/.ci/openshift-ci/build-root/scripts/qs-overrides/microprofile-reactive-messaging-kafka/overridable-functions.sh#L66-L106

Kubernetes: 
https://github.com/wildfly/quickstart/blob/main/.github/workflows/scripts/kubernetes/qs-overrides/microprofile-reactive-messaging-kafka/overridable-functions.sh#L56-L95

I see in the CI code for both there is a 'pause' between the cluster and creating the topic. But I don't know if that is actually needed or not.

For OpenShift, I am pretty sure the break between creating the subscription and the cluster is needed. Unless it handles things differently for some reason when using one file.

The Kubernetes part is not in the README yet, it is part of https://github.com/wildfly/quickstart/pull/919 (@emmartins )

2024-06-12 08:55 UTC, kstekovi commented
Thanks for review @kabir 

Could you please take a look again? The CI is updated.

2024-06-12 13:24 UTC, kabir requested changes
Hi,

The changes **look** good but it doesn't run :-)

If you see the original OpenShift setup test script it used to install the operator, but then it needs to wait for the AMQ Streams operator to start and make the CRDs available. That was done here https://github.com/wildfly/quickstart/pull/929/files#diff-3002e707de1a81994b7bfc2d03e271afd1e186c1d8ee4c8ae7c70992bbddd5aaL62-L65. Later there is a check of the exit value from the oc calls to create the cluster. Once the oc call to create the cluster exits with 0 we can proceed.

As it is now, if I try to apply the file it fails when trying to install the cluster:

```
% oc apply -f ./charts/kafka-on-openshift.yaml --wait --timeout=10m0s
subscription.operators.coreos.com/amq-streams unchanged
resource mapping not found for name: "my-cluster" namespace: "" from "./charts/kafka-on-openshift.yaml": no matches for kind "Kafka" in version "kafka.strimzi.io/v1beta2"
ensure CRDs are installed first
resource mapping not found for name: "testing" namespace: "" from "./charts/kafka-on-openshift.yaml": no matches for kind "KafkaTopic" in version "kafka.strimzi.io/v1beta2"
ensure CRDs are installed first
```

So I think this needs to be two scripts. One for the subscription, and one for the cluster/topic. And there should b

2024-06-14 12:02 UTC, kstekovi commented
Hi, This didn't happen on my cluster. I try also different one and hit this problem. 

So i split resource definition into two yaml files which are processed separately as you suggest. Thanks.

2024-06-17 11:10 UTC, kabir requested changes
Hi @kstekovi A few small changes needed, but apart from that I've verified that both the README instructions and running the tests work against a Clusterbot instance.

So I think once you make the fixes I suggested, this can be merged

2024-06-17 12:08 UTC, kstekovi commented on microprofile-reactive-messaging-kafka/README-source.adoc
> +$ oc delete -f ./charts/kafka-on-openshift.yaml --wait --timeout=10m0s
I miss this. Instruction updated.

2024-06-17 12:12 UTC, kstekovi commented on microprofile-reactive-messaging-kafka/helm-install-prerequisites.adoc
> +on Apache Kafka. To deploy AMQ Streams in the Openshift environment:
line break removed.

2024-06-17 12:12 UTC, kstekovi commented on microprofile-reactive-messaging-kafka/helm-install-prerequisites.adoc
> +entity operator is up and running. The name of the pod will be of the format `my-cluster-entity-operator-xxxxxxxxx-yyyyy`.
line break removed.

2024-06-17 12:15 UTC, kabir approved these changes

2024-06-17 12:18 UTC, merged