WFLY-19790 Remove batch-processing DS file
wildfly/quickstart pull request #960
Opened 2024-09-30 14:52 UTC by liweinan

2024-09-30 15:57 UTC, liweinan commented
@jfdenise I don't know how to fix this error:

- https://github.com/wildfly/quickstart/actions/runs/11109598030/job/30865320646?pr=960#step:6:6605

As the `h2-database` has already been added. Could you please help check this? Thanks!

2024-10-03 11:42 UTC, emmartins requested changes

2024-10-03 11:48 UTC, emmartins commented
Besides the script change, guess we need instructions wrt the script execution when used with bare-metal standard distribution, and a config restore script too? You can reuse content from https://github.com/wildfly/quickstart/blob/484ba35272679919fca411d94e0072f0513c36b6/ee-security/README-source.adoc?plain=1#L40

2024-10-03 11:49 UTC, emmartins commented
Btw I really thought you would just need to update the persistence.xml, ie no need for config change script...
@scottmarlow I wonder if this (replace usage of the DS file with just persistence.xml) would be possible?

2024-10-07 11:27 UTC, liweinan commented
I discussed this issue with @jamezp, and the DS file may still be used in the future, so I am holding off on this work.

2024-10-07 11:30 UTC, liweinan commented on batch-processing/configure-server.cli
> +#reload
I can create another PR to do this if necessary.

2024-10-28 13:03 UTC, emmartins commented
@jamezp can you please clarify what @liweinan said above about new use for DS files? We have those deprecated for long, and we are logging a log warning (the reason for this issue) when deploying such files...

2024-10-29 10:10 UTC, liweinan commented
> One option is to simply use the default data source

btw here is one blog post that I'm writing on this topic: https://github.com/wildfly/wildfly.org/pull/677

If this is a better solution for this example, I can work on it.

2024-10-29 11:43 UTC, emmartins commented
really up to you guys what you want to use as datasource, be it standard or not I'm fine with it, just agree with QE it's no longer ok to use a -ds file to config a database, you now have the standard persistence.xml and DatasourceDefinition annotation that should be the alternative, or at least the first alternative, if the vendor requires something more (like a cli script then be it)

2024-10-30 14:35 UTC, liweinan commented
James has provided an example showing the CLI usage here: https://github.com/jberet/jberet-examples/pull/13

I'll use

2024-10-30 17:28 UTC, liweinan commented
@emmartins I have replaced Glow with the data source feature pack in combination with the CLI script to create the database and configure the datasource. Could you please check if this solution is acceptable? Thanks!

2024-10-30 17:29 UTC, liweinan commented
@jamezp I'm not sure how to fix the Kubernetes CI test failure. Could you please help to check it when you have time? Thanks!

2024-10-30 17:39 UTC, jamezp commented
@liweinan I have no idea why the Kubernetes tests are failing. There seems to be no indication as to why.

2024-10-30 18:13 UTC, emmartins commented on batch-processing/pom.xml
> -                            <discover-provisioning-info>
why are we going back to directly using galleon layers, instead of glow's discovery? This seems a mistake

2024-10-30 18:18 UTC, emmartins commented on batch-processing/pom.xml
> -                            <discover-provisioning-info>
Maybe you are just doing copy paste of outdated (in the sense of not using glow) configuration? You can use glow and pack a script as shown at https://github.com/wildfly/quickstart/blob/82ceea0a283cd1b7a2d1bdfd51a8c41b23e8b182/opentelemetry-tracing/pom.xml#L161

2024-10-30 19:00 UTC, emmartins commented on batch-processing/add-h2-ds.cli
> +xa-data-source add --name=batch_db --enabled=true --use-java-context=true --use-ccm=true --jndi-name=java:jboss/datasources/batch-processingDS --xa-datasource-properties={"URL"=>"jdbc:h2:mem:batch-pr
I still think you could do this op using only Jakarta specs, which would make this app portable among vendors. But I tried to use a DataSourceDefinition like the one below (you can add this for instance to Contact class) but boot failed with a CNFE for org.h2.jdbcx.JdbcDataSource. I guess we can try to explore the specs way and clarify how should users use the specs DataSourceDefinition later

@DataSourceDefinition(name="java:jboss/datasources/batch-processingDS",
        className="org.h2.jdbcx.JdbcDataSource",
        url="jdbc:h2:mem:batch-processing;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1",
        user="sa",
        password="sa"
)

2024-10-30 19:02 UTC, emmartins commented on batch-processing/pom.xml
> +                            <feature-packs>
we should revert this change too, other than adding the script of course

2024-10-30 19:03 UTC, emmartins requested changes
Please see my comments

2024-10-30 19:21 UTC, emmartins commented on batch-processing/add-h2-ds.cli
> +xa-data-source add --name=batch_db --enabled=true --use-java-context=true --use-ccm=true --jndi-name=java:jboss/datasources/batch-processingDS --xa-datasource-properties={"URL"=>"jdbc:h2:mem:batch-pr
nevermind, I was able to make it work, I will send an alternative PR for you to have a look

2024-10-30 20:17 UTC, emmartins commented
@liweinan @jamezp alternative PR using the specs DataSourceDefinition at https://github.com/wildfly/quickstart/pull/973

2024-10-31 01:13 UTC, liweinan commented
@emmartins Thanks for the review! I'll check it.

> alternative PR using the specs DataSourceDefinition at https://github.com/wildfly/quickstart/pull/973

Cool! I'll see if this can work with this example.

2024-10-31 17:45 UTC, liweinan commented
I closed this PR because it's been replaced by the PR mentioned above.

2024-10-31 17:45 UTC, closed without merging